# Generated by Django 4.1.6 on 2023-04-09 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('rental_company', models.CharField(max_length=50)),
                ('pick_up_location', models.CharField(max_length=250)),
                ('return_location', models.CharField(max_length=250)),
                ('pick_up_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_name', models.CharField(max_length=250)),
                ('summary', models.TextField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_name', models.CharField(max_length=250)),
                ('lat', models.CharField(max_length=20)),
                ('long', models.CharField(max_length=20)),
                ('itinerary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sights', to='moose_api.itinerary')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moose_api.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('itinerary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='moose_api.itinerary')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_type', models.CharField(max_length=250)),
                ('departure', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250, null=True)),
                ('return_date', models.DateField(null=True)),
                ('departure_date', models.DateField(null=True)),
                ('itinerary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='moose_api.itinerary')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='itinerary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='moose_api.itinerary'),
        ),
        migrations.AddField(
            model_name='car',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Affinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity_type', models.CharField(max_length=250)),
                ('itinerary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities', to='moose_api.itinerary')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
