# Generated by Django 4.1.6 on 2023-04-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moose_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
