# Generated by Django 4.1.6 on 2023-03-14 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moose_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wine',
        ),
    ]
