# Generated by Django 4.1.6 on 2023-03-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moose_api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
