# Generated by Django 4.1.6 on 2023-03-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moose_api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_company',
            field=models.CharField(default='', max_length=250),
        ),
    ]
