# Generated by Django 4.1.6 on 2023-03-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moose_api', '0004_itinerary_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(null=True),
        ),
    ]
