# Generated by Django 4.1.6 on 2023-04-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moose_api', '0004_itinerary_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='flight_id',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='moose_api.flight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='hotel_id',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='moose_api.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sight',
            name='lat',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sight',
            name='long',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(null=True),
        ),
    ]
