# Generated by Django 4.1.6 on 2023-04-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moose_api', '0005_itinerary_flight_id_itinerary_hotel_id_sight_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='flight_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moose_api.flight'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='hotel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moose_api.hotel'),
        ),
    ]
