# Generated by Django 4.1.6 on 2023-03-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moose_api', '0005_alter_flight_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
