# Generated by Django 4.1.6 on 2023-04-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moose_api', '0006_alter_itinerary_flight_id_alter_itinerary_hotel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='flight_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moose_api.flight'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='hotel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moose_api.hotel'),
        ),
    ]
