# Generated by Django 4.1.6 on 2023-03-31 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moose_api', '0007_alter_flight_arrival_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrival_date',
            new_name='return_date',
        ),
    ]
