# Generated by Django 4.1.6 on 2023-04-04 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moose_api', '0007_alter_itinerary_flight_id_alter_itinerary_hotel_id'),
        ('moose_api', '0008_rename_arrival_date_flight_return_date'),
    ]

    operations = [
    ]
