# Generated by Django 4.1.6 on 2023-04-05 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moose_api', '0009_merge_20230403_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='flight_id',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='hotel_id',
        ),
        migrations.AlterField(
            model_name='affinity',
            name='itinerary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities', to='moose_api.itinerary'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='itinerary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='moose_api.itinerary'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='itinerary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='moose_api.itinerary'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='itinerary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='moose_api.itinerary'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='itinerary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sights', to='moose_api.itinerary'),
        ),
    ]
