# Generated by Django 4.1.6 on 2023-04-07 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moose_api', '0005_car_sight_lat_sight_long_alter_flight_departure_date_and_more'),
        ('moose_api', '0010_remove_itinerary_flight_id_remove_itinerary_hotel_id_and_more'),
    ]

    operations = [
    ]
